console.log("----------------------------------------------------------")
console.log("|********************************************************|")
console.log("|        DAV PUBLIC SCHOOL SARAMOHANPUR, DARBHANGA       |")
console.log("|                Year(2023-2022 )                        |")
console.log("|********************************************************|")
console.log("|                   REPORT CARD                          |")
console.log("|********************************************************|")
console.log("|                                                        |")
console.log("|                                                        |")
console.log("|                                                        |")
console.log("|      NAME:- Bhanu pratap singh    YEAR:-2022-2023      |")
console.log("|                                                        |")
console.log("|      ROLL:- 28                     TERM:-FINAL         |")
console.log("|********************************************************|")
console.log("|                                                        |")
console.log("|     SUBJET      |     GRADE1  |  GRADE2  |   GRADE3    |")
console.log("|********************************************************|")
console.log("|    Literature   |       A     |    A     |    A        |")
console.log("|                 |             |          |             |")
console.log("|                 |             |          |             |")
console.log("|                 |             |          |             |")
console.log("|     History     |       B+    |      B+  |      B+     |")
console.log("|                 |             |          |             |")
console.log("|                 |             |          |             |")
console.log("|                 |             |          |             |")
console.log("|     sst         |        B    |      B   |     B       |")
console.log("|                 |             |          |             |")
console.log("|                 |             |          |             |")
console.log("|     Art         |       C     |      C   |     C       |")
console.log("|                 |             |          |             |")
console.log("|                 |             |          |             |")
console.log("|********************************************************|")
console.log("----------------------------------------------------------")